### PR TITLE
airtime purchase for stax bonus airtime through paybill

### PR DESCRIPTION
**Pull request by alexosugo**

### CODE REVIEW

**Review by androidmaven — APPROVED** [review]
LGTM

**Review by davkutalek — CHANGES_REQUESTED** [review]
@alexosugo this is a lot of hardcoded details. Can we include this in the firebase config or even the config from maathai instead?

**Comment by alexosugo** [comment]
@davkutalek There's an open task between Steve and Sam to get the configs on Maathai. This PR was to be updated to revert everything back to how it was but use the new paybill configs instead. 

In the meantime, I'll set up the details on Firebase for this release.

**Comment by alexosugo** [comment]
@mijiga Have you been able to review this?

**Comment by mijiga** [comment]
@alexosugo now that the Maathai config has been done, the paybill action should be able to provide the required details(payroll number) and not need to pull from firebase nor hardcode. We should only need to hardcode the "STAX#" prefix

**Comment by alexosugo** [comment]
Thank you @mijiga. I'll effect the changes today.

**Review by mijiga — APPROVED** [review]
Looks good, nice work. @alexosugo

**Pull request merged**
