### PR TITLE
adding screenshots to errors

### PR DESCRIPTION
**Pull request by wachukxs**

### CODE REVIEW

**Comment by wachukxs** [comment]
Apparently we already capture user id in sentry, which I assume is the device ID

**Comment by davkutalek** [comment]
@wachukxs I wouldn't assume that, it may be automatic and different than our device ID. It would be good if they were the same if they aren't

**Comment by wachukxs** [comment]
@davkutalek you're right!! I've updated the PR.

**Review by davkutalek — CHANGES_REQUESTED** [review]
Configuration options like this don't belong in a Fragment, they are normally set in the launch activity or ApplicationInstance. In this case they actually go in the SDK in the `AnalyticsSingleton`. I think the Android Manifest change is fine here cause we don't want screenshots from developer's apps.

**Comment by wachukxs** [comment]
@davkutalek I've reverted the configurations changed I made in the Fragment file. Just need one last review from you on this.

**Review by davkutalek — APPROVED** [review]

**Pull request merged**
