### PR TITLE
fixed Formatting issue in mapped flow detail page

### PR DESCRIPTION
**Pull request by androidmaven**

### CODE REVIEW

**Review by davkutalek — APPROVED** [review]
Looks good. The flow_done_desc string doesn't have to have CDATA this way?

**Comment by androidmaven** [comment]
The  flow_done_desc is just plain text.

**Comment by davkutalek** [comment]
> The flow_done_desc is just plain text.

It is being used inside the HTML call, so was just curious

**Comment by androidmaven** [comment]
That's true. I'll update that with a commit. Thanks for pointing this out.

**Pull request merged**
